# Setup
title:               自由に 考え
tagline:             'Think freely'
description:         'Check out the links below for more content'
url:                 https://blog.jiyuu-ni.net
baseurl:             ''
paginate:            5
permalink:           pretty

excerpt_separator: <more />

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# TOC configuration
my_toc_min: 1
my_toc_max: 3
my_toc_ordered: true
my_toc_item_class: 'toc-section'
my_toc_submenu_class: 'toc-subsection'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
#permalink: /:year/:month/:day/:title
